[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
providers = ["node"]

[deploy]
startCommand = "pnpm run preview --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
VITE_API_URL = "${{BACKEND_URL}}"

