[build]
builder = "DOCKERFILE"


[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
FLASK_ENV = "production"
FLASK_DEBUG = "False"
HOST = "0.0.0.0"

