[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
providers = ["python"]

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 src.main:app"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
FLASK_ENV = "production"
PYTHONPATH = "/app"

