[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ON_FAILURE"

[start]
cmd = "pip install Flask==3.0.0 Flask-CORS==4.0.0 requests==2.31.0 && python -c \"from flask import Flask, jsonify; app=Flask(__name__); app.route('/')(lambda: {'status': 'running', 'service': 'LEED.io API'}); app.route('/api/health')(lambda: {'status': 'healthy'}); app.run(host='0.0.0.0', port=int(__import__('os').environ.get('PORT', 8080)))\""
